# Cloudflare Workers configuration for CubaModel Bot
name = "cubamodel-bot"
main = "src/worker.js"
compatibility_date = "2024-08-20"
compatibility_flags = ["nodejs_compat"]

# Environment variables
[vars]
NODE_ENV = "production"
BOT_VERSION = "2.2.0"

# Secrets managed with `wrangler secret put ...`:
# - BOT_TOKEN (Telegram Bot Token)
# - SUPABASE_URL (Supabase project URL)
# - SUPABASE_SERVICE_ROLE_KEY (Supabase service role key)
# - TG_WEBHOOK_SECRET (Random string for webhook security)
# - ADMIN_TG_IDS (Comma-separated admin user IDs)
# - ALLOWED_CHAT_IDS (Comma-separated allowed chat IDs, optional)

# Optional KV namespaces for event logging
# [[kv_namespaces]]
# binding = "EVENTS_KV"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# Build configuration
[build]
command = ""

# Development configuration
[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"
