# Cloudflare Workers configuration
name = "cubamodel-bot"
main = "src/worker.js"
compatibility_date = "2024-08-20"

# Secrets managed with `wrangler secret put ...`:
# - BOT_TOKEN (Telegram)
# - SUPABASE_URL
# - SUPABASE_SERVICE_ROLE_KEY (service role; only in Worker)
# - TG_WEBHOOK_SECRET (random long string)
# - ADMIN_TG_IDS (csv)
# - ALLOWED_CHAT_IDS (csv, optional)

[vars]
NODE_ENV = "production"
